version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/init.sh
      timeout: 300
      runas: root
    - location: scripts/run.sh
      timeout: 300
      runas: root
